- name: Install Apache and Httpd
  hosts: all
  become: true
  tasks:
    - name: Install Apache on Debian-based systems
      apt:
        name: apache2
        state: latest
      when: ansible_os_family == "Debian"
    - name: Install Httpd on RedHat-based systems
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"