- name: my 1st playbook
  hosts: all
  vars:
    greeting: "Hello, World!"  #Global variable
  vars_files:
    - ./var.txt
    - ./var2.txt   #File variable
  tasks:
    - name: Print tasks
      debug:
        msg: "This is my first Ansible playbook!"
    - name: my name
      debug:
        msg: "My name is {{ name }}"
      # vars:
      #   name: "Sakshi Jain"  #Local variable
    - name: Print greeting
      debug:
        msg: "{{ greeting }}"