- name: my 1st playbook
  hosts: all
  vars:
    greeting: "Hello, World!"  #Global variable
  # vars_files:
  #   - ./var.txt
  #   - ./var2.txt   #File variable
  vars_prompt:
    - name: "name"
      prompt: "Enter your name"
      private: false   #Prompt variable
  tasks:
    - name: Print tasks
      debug:
        msg: "This is my first Ansible playbook!"
    - name: my name
      debug:
        msg: "My name is {{ name }}"
      # vars:
      #   name: "Sakshi Jain"  #Local variable
    - name: Print greeting
      debug:
        msg: "{{ greeting }}"
    - name: Run Command
      command: hostname      #resister variable
      register: host_output
    - name: Show Hostname
      debug:
        msg: "The hostname is {{ host_output.stdout }}"  